apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: nodejsdemo
  annotations:
    kubernetes.io/ingress.class: addon-http-application-routing
spec:
  rules:
    - http:
        paths:
          - path: /
            pathType: ImplementationSpecific
            backend:
              service:
                name: nodejsdemo
                port: 
                  number: 80